-- 1. Total Missions
Total Missions = COUNTROWS('cleaned_space_missions')

-- 2. Successful Missions
Successful Missions =
CALCULATE(
    COUNTROWS('cleaned_space_missions'),
    'cleaned_space_missions'[MissionStatus] = "Success"
)

-- 3. Failled Missions
Failed Missions =
CALCULATE(
    COUNTROWS('cleaned_space_missions'),
    'cleaned_space_missions'[MissionStatus] <> "Success"
)

-- 4. Retired Missions
Retired Missions =
CALCULATE(
    COUNTROWS('cleaned_space_missions'),
    'cleaned_space_missions'[MissionStatus] = "Retired"
)

-- 5. Success Rate
Success Rate = DIVIDE([Successful Missions], [Total Missions])

-- 6. Decade
  Decade = INT('cleaned_space_missions'[Year] / 10) * 10

-- 7. Total Launches
Total Launches = COUNTROWS('cleaned_space_missions')

-- 8. Successful Launches
Successful Launches = SUM('cleaned_space_missions'[SuccessFlag])

-- 9. Failed Launches
Failed Launches = SUM('cleaned_space_missions'[FailureFlag])

-- 10. Success Rate (%)
Success Rate (%) = 
DIVIDE(
    CALCULATE(COUNTROWS(cleaned_space_missions), cleaned_space_missions[MissionStatus] = "Success"),
    COUNTROWS(cleaned_space_missions)
)

-- 11. Average Launches per Year
Avg Launches per Year = AVERAGE('cleaned_space_missions'[Year])

-- 12 Top Organisations
Top Organization =
TOPN(
    1,
    SUMMARIZE(cleaned_space_missions, cleaned_space_missions[Company], "TotalMissions", COUNT(cleaned_space_missions[Mission])),
    [TotalMissions],
    DESC
)

